KEY_PLAY        = 'space'
KEY_STEP_FWD    = 'Right'
KEY_STEP_BWD    = 'Left'

KEY_RESET_GROUP     = ['BackSpace']
KEY_CAM_RESET       = ['r','KP_0']
KEY_CENTER_VIEW     = 'KP_5'
KEY_CAM_PROJ        = 'c'
KEY_ROT_YL          = 'KP_4'
KEY_ROT_YR          = 'KP_6'
KEY_ROT_XD          = 'KP_2'
KEY_ROT_XU          = 'KP_8'
KEY_TRUCK_L         = 'KP_4'
KEY_TRUCK_R         = 'KP_6'
KEY_PEDESTAL_U      = 'KP_8'
KEY_PEDESTAL_D      = 'KP_2'
KEY_TURNTABLE       = 'KP_Decimal'
TURNTABLE_ROT_STEP  = 5

KEY_VIEW_FRONT   = 'F1'
KEY_VIEW_BACK    = 'F2'
KEY_VIEW_SIDE_L  = 'F3'
KEY_VIEW_SIDE_R  = 'F4'
KEY_VIEW_TOP     = 'F5'
KEY_VIEW_BOTTOM  = 'F6'
KEY_AXIS_SWAP    = 'Tab'

KEY_KP_ZOOM_IN   = 'KP_7'
KEY_KP_ZOOM_OUT  = 'KP_9'
KEY_KP_DOLLY_IN  = 'KP_1'
KEY_KP_DOLLY_OUT = 'KP_3'

KEY_SCREENSHOT  = 'grave'
KEY_GRID        = '1'
KEY_GRID_ONLY   = 'semicolon'
KEY_BACKFACE    = 'b'
KEY_ACTOR_NEXT  = 'F12'
KEY_THEME       = 'F11'
KEY_OVERLAY        = 'slash'
KEY_LOG_OVERLAY    = 'period'
KEY_STATUS_TEXT    = 'comma'
KEY_SEQ_OVERLAY    = 'apostrophe'
KEY_HELP        = 'h'

KEY_FIRST_FRAME = 'Up'
KEY_LAST_FRAME  = 'Down'

KEY_MESH_DEFAULT    = 'q'
KEY_SMOOTH_SHADING  = 's'
KEY_VTX             = '2'
KEY_WIRE            = '3'
KEY_SMOOTH          = '4'
KEY_ISO             = '5'
KEY_LIGHT           = 'd'
KEY_NORMAL_COLOR    = '6'
KEY_MESH_QUALITY    = '7'
KEY_FACE_NORMAL     = '8'
KEY_DEPTH           = '9'
KEY_EDGE            = 'e'

KEY_INC         = 'KP_Add'
KEY_DEC         = 'KP_Subtract'
KEY_AXIS_NEXT   = 'Next'
KEY_AXIS_PREV   = 'Prior'
