CAM_DIST_FACTOR = 3.5
CAM_UP_VECTOR   = (0, 1, 0)
CAM_ZOOM_STEP   = 1.1
CAM_PAN_STEP    = 0.05
CAM_TRUCK_STEP  = 0.02

STARTUP_CAM_AZIMUTH     = 0.0
STARTUP_CAM_ELEVATION   = 5.0

STARTUP_TRUCK       = 0.0
STARTUP_PEDESTAL    = 0.0
STARTUP_DOLLY       = 0.0

STARTUP_FOCAL_LENGTH    = None

STARTUP_ZOOM            = None
