STARTUP_MODE_POINT_CLOUD = 'point_rgb'
POINTS_COLOR             = "#FFFFFF"

PT_SUBSAMPLE_THRESHOLD  = 500_000
PT_SUBSAMPLE_TARGET     = 300_000

PT_CLOUD_DEPTH_COLOR    = 'twilight'

PT_CLOUD_DEPTH_CONTRAST = 3.0
POINT_FOG               = True
POINT_FOG_START         = 0.7

PT_CLOUD_SIZE_DEFAULT     = 1
PT_CLOUD_SIZE_POINT_WHITE = 1
PT_CLOUD_SIZE_DEPTH       = 1
PT_CLOUD_SIZE_STEP        = 1
PT_CLOUD_SIZE_MIN         = 1
PT_CLOUD_SIZE_MAX         = 20

PT_CLOUD_SHADER_SCALE    = 9000.0
PT_CLOUD_SHADER_SIZE_MIN = 1.0
PT_CLOUD_SHADER_SIZE_MAX = 500.0

PT_STARTUP_AXIS           = None
PT_STARTUP_REVERSE_X_AXIS = None
PT_STARTUP_REVERSE_Y_AXIS = None
PT_STARTUP_REVERSE_Z_AXIS = None
PT_FLIP_OBJECT_X          = None
PT_FLIP_OBJECT_Y          = None
PT_FLIP_OBJECT_Z          = None
