WINDOW_TITLE         = 'vtkOpenGLMeshViewer'

WINDOW_ASPECT_RATIO  = 1.49074
WINDOW_WIDTH         = 1080
WINDOW_HEIGHT        = round(WINDOW_WIDTH * WINDOW_ASPECT_RATIO)
WINDOW_MONITOR_INDEX = 0

SHOW_GRID           = False
SHOW_BBOX           = False
SHOW_BACKFACE       = False
SHOW_LIGHTING       = True
SHOW_ANIMATION      = True
SHOW_TURNTABLE      = False
SHOW_HIDE_INFO      = False
SHOW_COLORBAR       = True
SHOW_IMAGE_SEQUENCE = True
SHOW_MESH           = True

STARTUP_AXIS            = 'OFF'
STARTUP_REVERSE_X_AXIS  = False
STARTUP_REVERSE_Y_AXIS  = False
STARTUP_REVERSE_Z_AXIS  = False

FLIP_OBJECT_X   = False
FLIP_OBJECT_Y   = False
FLIP_OBJECT_Z   = False

TARGET_ANIM_FPS         = 30
UPDATE_INTERVAL         = 0.016
UPDATE_INTERVAL_PLAY    = 0.033
TURNTABLE_STEP          = 1

NORM_SIZE       = 1.0
MAX_FRAME_SKIP  = 1
