NPY_AS_POINTCLOUD = True

DATA_NORMALIZE = True

DATA_NORMALIZE_VALUE = 10.0

DATA_NORMALIZE_AXIS = 'per_axis'

DATA_NORMALIZE_LOG = True

NP_STARTUP_MODE_POINT_CLOUD = 'depth'
NP_POINTS_COLOR             = '#FFFFFF'

NP_SUBSAMPLE_THRESHOLD  = 300_000
NP_SUBSAMPLE_TARGET     = 250_000

NP_CLOUD_DEPTH_COLOR    = 'Spectral'

NP_CLOUD_DEPTH_CONTRAST = 3.0
NP_POINT_FOG            = False
NP_POINT_FOG_START      = 0.7

NP_CLOUD_SIZE_DEFAULT     = 4
NP_CLOUD_SIZE_POINT_WHITE = 2
NP_CLOUD_SIZE_DEPTH       = 4
NP_CLOUD_SIZE_STEP        = 1
NP_CLOUD_SIZE_MIN         = 1
NP_CLOUD_SIZE_MAX         = 20

NP_CLOUD_SHADER_SCALE    = 9.0
NP_CLOUD_SHADER_SIZE_MIN = 1.0
NP_CLOUD_SHADER_SIZE_MAX = 500.0

NP_STARTUP_AXIS           = None
NP_STARTUP_REVERSE_X_AXIS = None
NP_STARTUP_REVERSE_Y_AXIS = None
NP_STARTUP_REVERSE_Z_AXIS = None
NP_FLIP_OBJECT_X          = None
NP_FLIP_OBJECT_Y          = None
NP_FLIP_OBJECT_Z          = None
