LBL_ISOLINE         = 'ISOLINE'
LBL_WIREFRAME       = 'WIREFRAME (VTX.NORM)'
LBL_REDUCTION       = 'MESH.REDUCTION'
LBL_SURF_NORMAL     = 'SURF.NORM'
LBL_QUALITY         = 'MESH.QUALITY'
LBL_VERTICES        = 'VERTICES (SPATIAL.INTV)'
LBL_FACE_NORMAL     = 'FACE.NORM'
LBL_DEPTH           = 'DEPTH'
LBL_EDGE            = 'EDGE.EXTRACT'
LBL_SURF_SMOOTHING  = 'SURF.SMOOTHING'

SMOOTH_CYCLE_LABELS = (
    'PBR + TEX',
    'TEX',
    'PBR.SHADER',
)

LBL_MESH_HIDDEN     = 'MESH HIDDEN'
LBL_MESH_VISIBLE    = 'MESH VISIBLE'
LBL_EDGE_HIDDEN     = 'EDGE HIDDEN'
LBL_EDGE_VISIBLE    = 'EDGE VISIBLE'
LBL_BFC_ON          = 'BACK-FACE.CULLING: ON'
LBL_BFC_OFF         = 'BACK-FACE.CULLING: OFF'

LBL_GRID            = 'GRID + BBOX'
LBL_TURNTABLE       = 'AUTO.ROT: ON'
LBL_PLAY_ON         = 'PLAY'
LBL_PLAY_OFF        = 'PAUSE'

LBL_RESET_FULL          = 'RESET.FULL'
LBL_RESET_CAM           = 'RESET.CAM'
LBL_CENTER_VIEW         = 'CENTER.VIEW'
LBL_TRUCK_L             = 'TRUCK.L'
LBL_TRUCK_R             = 'TRUCK.R'
LBL_PEDESTAL_U          = 'PEDESTAL.U'
LBL_PEDESTAL_D          = 'PEDESTAL.D'
LBL_DEFAULT             = 'DEFAULT'
LBL_SCREENSHOT          = 'SCREENSHOT SAVED'
LBL_CAM_PARALLEL        = 'CAMERA: PARALLEL'
LBL_CAM_PERSPECTIVE     = 'CAMERA: PERSPECTIVE'
LBL_VIEW_FRONT          = 'VIEW: FRONT'
LBL_VIEW_BACK           = 'VIEW: BACK'
LBL_VIEW_SIDE_L         = 'VIEW: SIDE.LEFT'
LBL_VIEW_SIDE_R         = 'VIEW: SIDE.RIGHT'
LBL_VIEW_TOP            = 'VIEW: TOP'
LBL_VIEW_BOTTOM         = 'VIEW: BOTTOM'

LBL_PT_CLOUD_RGB        = 'POINTS.RGB'
LBL_PT_CLOUD_WHITE      = 'POINTS'
LBL_PT_CLOUD_DEPTH      = 'POINTS.DEPTH'
LBL_PT_FOG_ON           = 'POINTS.FOG: ON'
LBL_PT_FOG_OFF          = 'POINTS.FOG: OFF'

LBL_FRAME_FIRST         = 'FRAME.FIRST'
LBL_FRAME_LAST          = 'FRAME.LAST'

FMT_ACTOR_CYCLE         = 'ACTOR: {}/{}'

FMT_HDRI_ROT        = 'LIGHTING.ROT: {:.1f}'
FMT_EDGE_ANGLE      = 'EDGE.ANGLE: {:.1f}'
FMT_ISO_COUNT       = 'ISO.COUNT: {}'
FMT_VTX_INTERVAL    = 'VTX.INTV: {:.4f}'
FMT_MESH_RED        = 'MESH.REDUCTION: {:.2f}'
FMT_PT_SIZE         = 'POINT SIZE: {}'
FMT_ISO_AXIS        = 'ISO.AXIS: {}'
FMT_DEPTH_AXIS      = 'DEPTH.AXIS: {}'
FMT_WIRE_AXIS       = 'WIRE.AXIS: {}'
FMT_NORMAL_AXIS     = 'NORMAL.AXIS: {}'

AXIS_NAMES = ('X', 'Y', 'Z', 'CAM')

AXIS_SWAP_NAMES = ('OFF', 'Y\u2194Z', 'X\u2194Z', 'X\u2194Y')
FMT_AXIS_SWAP   = 'AXIS.SWAP: {}'
